import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/global/theme-provider";
import Sidebar from "@/components/global/sidebar/sidebar";

export const metadata: Metadata = {
  title: "PocketFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-w-screen min-h-screen flex flex-row">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          //disableTransitionOnChange
        >
          <Sidebar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
